1st Program

#include <iostream>
using namespace std;

int main()
{
int x = -1;
cout << "Before try \n";
try {
	cout << "Inside try \n";
	if (x < 0)
	{
		throw 'a';
		cout << "After throw (Never executed) \n";
	}
}
catch (int x ) {
	cout << "Exception Caught \n";
}
catch (char x ) {
	cout << "sadasd Caught \n";
}
cout << "After catch (Will be executed) \n";
return 0;
}













2nd Program

#include<iostream>
using namespace std;

void fun2(int k)
{
    try{
        if(k>10)
        throw k;
    }
    catch (int e)
    {
        cout<<"Hi "<<e<<endl;
        throw 99;
    }
}

void fun1(int x)
{
    try{
        fun2(x);
    }
    catch (int e)
    {
        cout<<"hey "<<e<<endl;
    }
    
    
}


int main()
{
    fun1(12);
    return 0;
}





3rd Program

#include<iostream>
using namespace std;

void fun3(const string& newsfeed)
{
    try{
        if(newsfeed=="FRC")
        throw newsfeed;
    }
    catch (const string& e)
    {
        cout<<"Hi "<<e<<endl;
        throw 99;
    }
}

void fun2(const string& newsfeed)
{
    fun3(newsfeed);
}
void fun1(const string& x)
{
    try{
        fun2(x);
    }
    catch (int e)
    {
        cout<<"hey "<<e<<endl;
    }
    
    
}


int main()
{
    const string& a="FRC";
    fun1(a);
    return 0;
}
